/**
 * Chữ của Bài 3 "Khuôn riêng, mẫu chung" (màn 7, Làng Khắc Dấu). Xem content/HUONG-DAN-SUA-CHU.md.
 * Chỗ giữ tên: {chuDung}, {bacAn}, {cuBinh}, {coChi}, {phanDien} là nhân vật; {myName} là tên người chơi;
 * {n}, {x}, {testedKey}… là số do bài điền vào.
 * Toán, bảng khóa, cách tạo đề và chấm sao nằm ở lessons/bai-3 (logic); ở đây chỉ có chữ hiển thị.
 *
 * LƯU Ý: các chuỗi dưới nhóm `giaoDich` và `Chuyển … xu cho …` là nội dung được KÝ (băm). Đổi một chữ là chữ ký đổi theo,
 * bảng test chữ ký sẽ đỏ. Muốn đổi tên hiển thị thì sửa ở chỗ khác, đừng sửa các chuỗi này.
 */
import type { LessonContent } from '../../lesson2d/types';

/** Ảnh nền của màn 7 trong manifest (không đuôi) */
export const BAI3_BACKGROUND = 'scenes/bai-hoc-lang-khac-dau';

/** Nội dung dùng cho khung LessonPage2D: lời chú Dũng theo thời điểm, lời trao trang, giới thiệu 3 trạm, thẻ "Em có biết?". */
export const bai3Lesson: LessonContent = {
  dialogue: {
    /** Đầu bài (trước trạm Dễ) */
    dauBai: [
      {
        characterId: 'chuDung',
        text: 'Khuôn riêng cất kín, chỉ cháu biết. Mẫu công khai thì treo cho cả làng xem. Có mẫu, ai cũng kiểm được dấu thật hay giả.',
      },
    ],
    /** Trước trạm Trung bình */
    truocTb: [
      {
        characterId: 'chuDung',
        text: '{phanDien} vừa gửi mấy lá thư giả, còn kèm cả mẫu dấu tự làm. Nhớ chỉ tin bảng mẫu của làng thôi!',
      },
    ],
    /** Bài này không có lời trước trạm Khó */
    truocKho: [],
    /** Cuối bài, trước màn hoàn thành */
    cuoiBai: [{ characterId: 'chuDung', text: 'Mất khuôn riêng là mất hết, không ai lấy lại giúp được đâu.' }],
  },

  /** "Kết thúc làng": cảnh trao Trang Sổ Vàng thứ ba */
  award: {
    chuThich: 'Chú Dũng trao Trang Sổ Vàng thứ ba.',
    loi: [
      {
        characterId: 'chuDung',
        text: 'Không giả dấu được nữa, {phanDien} chuyển sang trò trộn giao dịch ở Làng Bạc rồi.',
      },
    ],
  },

  /** Giới thiệu từng trạm (LevelIntro); mẹo do Bi nói */
  stations: {
    de: {
      tieuDe: 'Đóng dấu và soi dấu',
      mucTieu: 'Dùng khóa riêng ký giao dịch, rồi tính khóa công khai cho 5 bạn.',
      meo: 'Công thức tính khóa công khai: 5^x mod 23.',
    },
    tb: {
      tieuDe: 'Hòm thư có kẻ mạo danh',
      mucTieu: 'Dùng Máy xác minh và Danh bạ để tìm 2 giao dịch mạo danh.',
      meo: 'Đừng tin khóa đính kèm trên giao dịch! Hãy luôn so với Danh bạ công khai.',
    },
    kho: {
      tieuDe: 'Làm thử {phanDien}: đoán ngược khóa riêng',
      mucTieu: 'Thử bẻ khóa với số nhỏ, số lớn và hiểu lý do bảo mật của blockchain.',
      meo: 'Khóa 256-bit an toàn vì số khả năng vượt xa sức mạnh của mọi siêu máy tính.',
    },
  },

  /** "Điều em vừa học" ở màn hoàn thành cả bài */
  keyTakeaway: 'Khóa riêng để ký, khóa công khai để người khác kiểm tra. Mất khóa riêng là mất hết, không ai lấy lại giúp được.',

  /** Thẻ "Em có biết?" (giữ thuật ngữ thật: khóa riêng, khóa công khai, chữ ký số) */
  emCoBiet: [
    {
      title: 'Chữ ký trên giấy vs Chữ ký số',
      text: 'Chữ ký trên giấy rất dễ bị tập đồ lại hoặc sao chép. Chữ ký số gắn chặt với từng nội dung cụ thể: đổi dù chỉ 1 đồng trong giao dịch, chữ ký sẽ lập tức vô hiệu!',
      example: 'Kẻ gian không thể cắt chữ ký từ giấy này dán sang giấy khác, vì chữ ký số được tính từ chính nội dung chuyển tiền.',
    },
    {
      title: 'Phép toán một chiều',
      text: 'Dễ đi xuôi, bất khả thi đi ngược. Ví dụ đời thực: thả một giọt mực vào cốc nước rất dễ, nhưng tách giọt mực trở lại thì không thể. Trong toán: tính 5^x mod 23 thì nhanh, nhưng biết kết quả tìm lại x thì cực khó.',
      example: '5^12 mod 23 = 18 tính rất nhanh. Nhưng biết 18 và bảo tìm lại 12 thì phải thử từng số một!',
    },
    {
      title: 'Cặp khóa trong Bitcoin (ECDSA)',
      text: 'Bitcoin dùng đường cong elip secp256k1. Khóa riêng là một số 256-bit (khoảng 77 chữ số thập phân). Số khả năng lớn hơn cả số nguyên tử trong toàn bộ vũ trụ quan sát được (~10^80)!',
      example: '115.792.089.237.316.195.423.570.985.008.687.907.853.269.984.665.640.564.039.457.584.007.913.129.639.936 khả năng!',
    },
    {
      title: 'Mất khóa riêng là mất vĩnh viễn',
      text: 'Không có ngân hàng nào để "quên mật khẩu", không có tổng đài hỗ trợ. Ước tính khoảng 3–4 triệu Bitcoin (trị giá hàng trăm tỷ USD) đã bị "chết vĩnh viễn" vì chủ nhân làm mất khóa riêng.',
      example: 'Hãy ghi khóa riêng ra giấy và cất vào nơi an toàn nhất, tuyệt đối không gửi lên mạng.',
    },
    {
      title: 'Địa chỉ ví chính là khóa công khai',
      text: 'Khi ai đó xin "địa chỉ ví" để gửi tiền cho em, họ đang xin một dạng rút gọn của khóa công khai. Cho người khác biết địa chỉ ví hoàn toàn an toàn — họ chỉ có thể gửi tiền vào, không thể rút tiền ra.',
      example: 'Khóa công khai giống số tài khoản ngân hàng, còn khóa riêng là mật khẩu rút tiền.',
    },
  ],
};

/**
 * Chuỗi do hàm trong lessons/bai-3 (logic) tạo ra. Là dữ liệu được ký, giữ ĐÚNG từng chữ của giai đoạn 1.
 * `thongDiep`: "Chuyển {n} xu cho {nguoi}" với {nguoi} là tên người chơi (mặc định "Em").
 */
export const bai3Logic = {
  thongDiep: 'Chuyển {n} xu cho {nguoi}',
  /** Số ước tính ở trạm Khó (kiểu Việt Nam: dấu phẩy thập phân) */
  uocTinh: {
    totalPossibilities: '1,16 × 10^77',
    supercomputerTriesPerSec: '10^18',
    supercomputerYears: '3,7 × 10^51',
    smartSteps: '2^128',
    smartYears: '1,1 × 10^13',
    universeAgeYears: '13,8 tỷ',
    universeMultiplier: 780,
  },
} as const;

/** Tên 5 bạn ở trạm Dễ (khóa riêng 3, 5, 6, 7, 9). Người có khóa riêng 7 tên là "Lan" để khỏi trùng thầy Linh (spec 01). */
export const bai3Names = { giang: 'Giang', hoa: 'Hoa', khang: 'Khang', lan: 'Lan', minh: 'Minh' } as const;

/** Chữ bên trong 3 trạm. Khóa tNN theo thứ tự xuất hiện trong từng thành phần. */
export const bai3Texts = {
  easy: {
    t01: 'Kéo thẻ giao dịch vào đây',
    t02: '⚙️ Thả vào máy xác minh',
    t03: '⚙️ Cho thẻ của {phanDien} vào máy',
    t04: 'Chạm để đặt thẻ vào máy',
    t05: 'Hoặc kéo thả thẻ vào máy',
    t06: 'Chạm để gỡ thẻ về khay',
    t07: 'Chuyển 3 xu cho An',
    t08: 'Chuyển 5 xu cho Bình',
    t09: 'Chuyển 7 xu cho Chi',
    t10: 'Chuyển 50 xu từ {myName} cho {phanDien}',
    t11: 'bấm {nextN} lần → khóa riêng {nextN} ra khóa công khai {nextK}',
    t12: 'Gợi ý: 5^x: nhân 5 đủ x lần, mỗi lần lấy dư cho 23 (có thể dùng Máy tính nhanh bên dưới).',
    t13: 'Khóa riêng tạo ra chữ ký, khóa công khai để bất kỳ ai cũng đối chiếu được. Kẻ mạo danh không thể giả mạo chữ ký vì không có khóa riêng!',
    t14: 'Phần 1: Ký giao dịch & Thử máy xác minh',
    t15: 'Phần 2: Ghép cặp khóa công khai cho 5 bạn',
    t16: 'Trạm Dễ',
    t17: 'khóa công khai = g',
    t18: 'khóa riêng',
    t19: 'g = 5: số gốc, cả lớp dùng chung, ai cũng biết.',
    t20: 'p = 23: số chia lấy dư, cũng dùng chung, ai cũng biết.',
    t21: 'khóa riêng: số bí mật của riêng em.',
    t22: 'mod 23: lấy phần dư khi chia cho 23. Ví dụ 25 mod 23 = 2.',
    t23: 'Bạn nào có khóa riêng 3 thì: 5',
    t24: ' = 5 × 5 × 5 = 125. Rồi 125 mod 23 = 10 (vì 125 = 5 × 23 + 10). Vậy khóa công khai của bạn ấy là 10.',
    t25: 'Khóa riêng của em là số nào thì két sắt bên dưới giữ. Thẻ tên công khai là kết quả sau khi thay vào công thức trên.',
    t26: 'Két sắt bí mật của {myName}',
    t27: '👁️ Ẩn khóa',
    t28: '👁️ Mở xem',
    t29: 'Chỉ một mình em giữ, dùng để ',
    t30: '. Tuyệt đối không để lộ!',
    t31: 'ký tên',
    t32: 'Khóa riêng:',
    t33: 'Thẻ tên công khai của {myName}',
    t34: 'Ai cũng biết khóa này để ',
    t35: ' của em.',
    t36: 'đối chiếu chữ ký',
    t37: 'Khóa công khai:',
    t38: ' Bước 1: Chọn giao dịch và đóng chữ ký của em',
    t39: 'Chọn một giao dịch mẫu bên dưới rồi bấm ',
    t40: 'Ký bằng khóa riêng của em',
    t41: '✍️ Ký bằng khóa riêng của em',
    t42: 'Thẻ giao dịch đã ký của {myName} (kéo hoặc chạm để đưa vào máy):',
    t43: 'Đổi một chữ trong nội dung là cả hai số đổi theo.',
    t44: 'Máy xác minh',
    t45: 'Đang quét...',
    t46: 'Khớp!',
    t47: 'Sẵn sàng',
    t48: 'Máy sẽ tra Danh bạ công khai xem chữ ký trên thẻ này có khớp với khóa nào không.',
    t49: '✓ Chữ ký chính chủ!',
    t50: 'Khớp hoàn hảo với khóa công khai 18 của {myName}.',
    t51: 'Tiếp theo: Xem {phanDien} gian lận ➔',
    t52: '{phanDien} định mạo danh {myName}!',
    t53: '{phanDien} lén viết giao dịch: ',
    t54: '. Nhưng vì {phanDien} ',
    t55: ', {phanDien} đành liều ký bằng khóa riêng 13 của {phanDien}!',
    t56: '"Chuyển 50 xu từ {myName} cho {phanDien}"',
    t57: 'không có khóa riêng của em',
    t58: 'Thẻ gian lận do {phanDien} tạo (kéo hoặc chạm để đưa vào máy):',
    t59: '{myName} (bị {phanDien} mạo danh)',
    t60: 'Báo động!',
    t61: '✗ Phát hiện gian lận!',
    t62: 'Chữ ký trên thẻ ',
    t63: ' với khóa 18 của {myName}, mà lại khớp với khóa 21 của ',
    t64: 'không khớp',
    t65: '{phanDien}',
    t66: 'Sang phần 2: Ghép cặp khóa ➔',
    t67: ' Nhiệm vụ: Tìm khóa công khai cho 5 bạn',
    t68: 'Mỗi bạn có một ',
    t69: '. Công thức tính khóa công khai là: ',
    t70: '. Kéo hoặc chạm chọn một thẻ khóa bên dưới rồi gắn vào ô của bạn tương ứng (chạm ô có thẻ để gỡ về khay)!',
    t71: 'Khóa riêng x',
    t72: 'Khóa riêng: ',
    t73: 'Kho thẻ khóa công khai (7 thẻ gồm 2 thẻ bẫy):',
    t74: 'Kéo thẻ hoặc chạm chọn để gắn vào ô',
    t75: 'Đã gắn hết các thẻ lên các bạn. Hãy bấm "Kiểm tra kết quả"!',
    t76: 'Kiểm tra kết quả ➔',
    t77: 'Máy tính nhanh mod 23:',
    t78: 'Nhập hai số để nhân, máy trả về phần dư khi chia cho 23. Dùng khi em muốn tự kiểm tra một phép nhân.',
    t79: 'Nhân dồn 5:',
    t80: 'Mỗi lần bấm × 5 là nhân thêm một lần 5 rồi lấy dư cho 23 luôn. Bấm x lần thì được 5^x mod 23, chính là khóa công khai của khóa riêng x.',
    t81: 'Đã bấm 0 lần (bắt đầu từ 1)',
    t82: 'Đã bấm ',
    t83: ' lần → khóa công khai của khóa riêng ',
    t84: ' là ',
    t85: 'Về đầu',
    t86: 'Muốn tìm khóa công khai của Giang (khóa riêng 3)? Bấm Về đầu rồi bấm × 5 ba lần.',
    t87: 'Lịch sử (tối đa 6 dòng gần nhất):',
    t88: 'Chữ ký gồm hai con số',
    t89: 'Đóng hộp thoại',
    t90: 'Chữ ký của em không phải chữ viết tay. Nó là hai con số, ',
    t91: ' và ',
    t92: ', do máy tính ra.',
    t93: 'Ví dụ em ký câu \'Chuyển 3 xu cho An\':',
    t94: '1. Máy bốc một số ngẫu nhiên chỉ dùng cho lần ký này, giả sử là ',
    t95: '2. Từ số ',
    t96: ' đó, máy tính ra ',
    t97: '. Đây là dấu niêm phong của riêng lần ký này.',
    t98: '3. Máy trộn khóa riêng ',
    t99: ' của em với nội dung câu trên, ra ',
    t100: '4. Chữ ký là ',
    t101: '. Em gửi cả câu và hai số này đi.',
    t102: 'Vì sao không ai giả được:',
    t103: 'Người nhận lấy khóa công khai ',
    t104: ' của em, ghép với ',
    t105: ' rồi tính lại. Khớp thì đúng là em ký.',
    t106: 'Kẻ mạo danh không có khóa riêng ',
    t107: ', nên không tính được số ',
    t108: ' đúng. Nó ký thì ra hai số khác, ghép với khóa công khai ',
    t109: ' là lệch ngay.',
    t110: 'Đổi một chữ trong nội dung cũng lệch: cùng một chữ ký mà nội dung khác đi là không khớp nữa.',
    t111: 'Em không phải tự tính r và s. Máy làm việc đó.',
    t112: 'Đã hiểu',
  },
  medium: {
    t04: 'Khóa lạ (không có trong danh bạ)',
    t05: 'Xuất sắc! Em đã thẩm định chính xác cả 4 giao dịch!',
    t06: 'Em đã biết đối chiếu chữ ký với Danh bạ công khai thay vì vội tin vào khóa đính kèm của kẻ mạo danh.',
    t07: 'Đây chính là nguyên lý bảo mật căn bản của ví blockchain!',
    t08: 'Không bao giờ tin khóa công khai tự đính kèm trên giao dịch. Luôn đối chiếu chữ ký với Danh bạ công khai chính thức!',
    t09: 'Có {so} giao dịch thẩm định chưa đúng ({wrongNames}).',
    t10: 'Kẻ mạo danh có thể đính kèm khóa riêng của hắn để chữ ký hợp lệ với khóa đó, nhưng khóa đó KHÔNG thuộc về người gửi trong Danh bạ chính thức!',
    t11: 'Hãy bấm "Thử lại": thử từng giao dịch với đúng khóa của người gửi trong Danh bạ xem có khớp không nhé.',
    t18: 'Trạm Trung bình',
    t19: 'Lần thử: #{attempts}',
    t20: 'Thẩm định 4 giao dịch: Tìm ra 2 giao dịch mạo danh',
    t21: 'Dùng Máy xác minh để đối chiếu chữ ký. Khóa nào đáng tin thì em tự cân nhắc.',
    t22: 'Nộp kết quả thẩm định ➔',
    t23: ' Lưu ý quan trọng về Khóa đính kèm!',
    t24: '✕ Đã hiểu',
    t25: 'Khóa đính kèm là do ',
    t26: '. Kẻ mạo danh có thể đính kèm khóa của chính hắn — chữ ký sẽ khớp với khóa này, nhưng khóa này ',
    t27: ' của người bị mạo danh!',
    t28: 'người tạo thẻ tự dán vào',
    t29: 'KHÔNG CÓ trong Danh bạ',
    t30: 'kéo hoặc chạm chọn: 1 khóa + 1 giao dịch',
    t31: ' 4 Thẻ giao dịch cần thẩm định',
    t32: 'Đã chọn: {so}/4',
    t33: 'Máy xác minh chữ ký dùng thế nào?',
    t34: 'Đưa ',
    t35: ' và ',
    t36: ' vào máy, rồi bấm ',
    t37: '1 khóa',
    t38: '1 giao dịch',
    t39: '"Kiểm tra chữ ký"',
    t40: ' Chữ ký trên thẻ khớp với khóa em đưa vào.',
    t41: 'Đèn xanh:',
    t42: ' Chữ ký không khớp với khóa em đưa vào.',
    t43: 'Đèn đỏ:',
    t44: ' Quan trọng:',
    t45: 'Máy ',
    t46: ' phân biệt thẻ thật hay thẻ giả. Máy chỉ kiểm tra chữ ký có khớp với khóa được đưa vào hay không.',
    t47: 'KHÔNG',
    t48: 'Việc chọn khóa nào để đưa vào máy (khóa trong danh bạ hay khóa đính kèm) là do em quyết định.',
    t49: 'Đã hiểu',
    t50: 'Tuyệt vời!',
    t51: 'Thử lại vòng mới',
  },
  hard: {
    t01: 'p = 101 (Nhỏ)',
    t02: 'p = 1.009 (Vừa)',
    t03: 'p = 1.000.003 (Lớn)',
    t04: '{secs} giây',
    t05: '{m} phút {s} giây',
    t06: '{m} phút',
    t07: 'khoảng {so} giờ (~{days} ngày)',
    t08: 'khoảng {so} giờ',
    t09: 'khoảng {so} ngày (~{so2} giờ)',
    t10: 'khoảng {so} năm (~{so2} giờ)',
    t11: 'Ngân hàng',
    t12: 'Blockchain không có ngân hàng nào đứng giữa. Không ai giữ sổ hộ em, nên cũng không ai mở khóa hộ em được.',
    t13: 'Người lập trình ra blockchain',
    t14: 'Họ viết ra luật chơi rồi thôi. Họ cũng không có khóa riêng của em, và không có cửa sau nào để lấy tiền trong ví người khác.',
    t15: 'Các node trong mạng',
    t16: 'Các node chỉ kiểm tra chữ ký có hợp lệ không. Không có chữ ký thì mọi node đều từ chối, dù có bao nhiêu node đi nữa.',
    t17: 'Không ai cả',
    t18: 'Phép toán 5^x mod p là hàm một chiều: tính xuôi dễ, giải ngược cực khó (bài toán logarit rời rạc). Mất khóa riêng là mất tiền vĩnh viễn!',
    t19: '{wrongExplanation} Thử chọn lại xem.',
    t20: 'Phần 1: Dò khóa riêng với số nhỏ (p = 23)',
    t21: '(Bước A: Em tự dò)',
    t22: '(Bước B: Kết luận số liệu)',
    t23: '(Bước C: Máy dò & Bitcoin)',
    t24: 'Phần 2: Thử nghiệm thực tế {so}',
    t25: 'Phần 3: Tình huống mất khóa riêng',
    t26: 'Trạm Khó',
    t27: '{phanDien} muốn bẻ khóa của {bacAn}!',
    t28: 'Bác An có khóa công khai là ',
    t29: '. Công thức tính là: ',
    t30: '. Liệu {phanDien} có tìm được ',
    t31: ' bằng cách thử lần lượt các số không?',
    t32: 'khóa riêng x',
    t33: ' Gợi ý cách {phanDien} dò ngược:',
    t34: '{phanDien} chỉ biết một điều: ',
    t35: ', và khóa công khai của {bacAn} là ',
    t36: 'khóa công khai = 5',
    t37: 'khóa riêng',
    t38: '{phanDien} không có cách nào tính ngược. Công thức chỉ chạy được một chiều: có khóa riêng thì tính ra khóa công khai, còn ngược lại thì không có phép tính nào cả.',
    t39: 'Vậy {phanDien} chỉ còn một cách: đoán. Đoán một số x, tính 5',
    t40: ' mod 23, xem có ra 19 không. Không ra thì đoán số khác.',
    t41: 'Khóa riêng chỉ từ 1 đến 22, nên nhiều nhất 22 lần đoán là ra. Em thử xem mất mấy lần.',
    t42: '📖 Xem lại bảng 5^x mod 23',
    t43: '(Chỉ mở sau khi em tự thử ít nhất 3 số)',
    t44: 'Nhập số x (1..22):',
    t45: 'Thử giá trị x',
    t46: 'Máy đang thử...',
    t47: '⚡ Để máy thử lần lượt',
    t48: ' Em tự thử ít nhất 3 số đã nhé (đã thử {so}/3 số khác nhau).',
    t49: ' ĐÃ TÌM RA KHÓA RIÊNG: x = 15!',
    t50: 'Vì tập hợp số chỉ từ 1 đến 22, ta chỉ cần thử tối đa ',
    t51: ' là chắc chắn tìm ra. Nhưng nếu số cực lớn thì sao?',
    t52: '22 lần',
    t53: 'Lịch sử thử nghiệm ({so} lần thử):',
    t54: '🤔 Với p = 23 thì em dò ra khóa riêng khá nhanh. Nếu p là một số rất lớn, em còn tìm được khóa riêng từ khóa công khai không?',
    t55: 'Vẫn tìm được, chỉ lâu hơn chút',
    t56: 'Tìm được nếu dùng máy tính mạnh',
    t57: 'Lâu tới mức coi như không tìm được',
    t58: ' Em thử xem sao.',
    t59: 'Sang phần 2: Thử với số lớn ➔',
    t60: 'Bước A: Em tự dò',
    t61: 'Thử sức tìm khóa riêng bằng tay',
    t62: 'Khóa công khai của {bacAn} là ',
    t63: '. Tìm khóa riêng x sao cho ',
    t64: 'Thời gian còn lại',
    t65: 'Nhập số x (1..1.000.001):',
    t66: 'Nhập số x...',
    t67: ' Em may mắn thật! Xác suất trúng mỗi lần thử chỉ là 1 trên 1.000.001.',
    t68: 'Xem kết luận số liệu ➔',
    t69: '5 lần thử gần nhất (Tổng số lần đã thử: {so}):',
    t70: '✓ Đúng',
    t71: '🏳️ Em thấy việc này là không thể — bỏ cuộc',
    t72: 'Bước B: Kết luận từ số liệu của em',
    t73: 'Thử bằng tay tốn bao nhiêu thời gian?',
    t74: 'Em đã thử ',
    t75: '. Với p = 1.000.003 có ',
    t76: ' khóa riêng có thể. Cứ tốc độ này, để thử hết em cần ',
    t77: ', không nghỉ.',
    t78: '{so} lần',
    t79: '💡 Lúc nãy em đoán là ',
    t80: '. Giờ em thấy thế nào?',
    t81: '💡 Lúc nãy em đã nhận định rất chuẩn xác: ',
    t82: 'Để máy thử xem nhanh hơn bao nhiêu ➔',
    t83: 'Bước C: Máy tính thử sức',
    t84: ' Thử nghiệm tốc độ dò khóa ngay trên trình duyệt',
    t85: 'Máy tính của em có thể thử hàng chục nghìn phép tính mỗi giây. Hãy thử bẻ khóa với các kích thước số khác nhau:',
    t86: 'Mục tiêu: {so}',
    t87: 'Cấu hình: p = {so}',
    t88: 'Đang chạy...',
    t89: 'Hoàn thành!',
    t90: 'Số phép thử',
    t91: 'Thời gian',
    t92: 'Tốc độ',
    t93: '✓ Tìm được khóa riêng {so} sau {so2} lần thử, mất {so3} ms',
    t94: ' So sánh thẳng:',
    t95: 'Máy làm xong việc em vừa bỏ cuộc trong khoảng ',
    t96: ' Máy nhanh hơn em khoảng ',
    t97: '{so} lần',
    t98: ' Nhưng Bitcoin dùng khóa 256-bit!',
    t99: 'Tổng số khả năng (2²⁵⁶):',
    t100: 'Lớn hơn toàn bộ số hạt nguyên tử trong vũ trụ quan sát được (~10⁸⁰)!',
    t101: 'Siêu máy tính thử {supercomputerTriesPerSec} lần/giây:',
    t102: '{supercomputerYears} năm',
    t103: 'Kể cả thuật toán thông minh nhất ({smartSteps} bước) cũng cần {smartYears} năm (gấp {universeMultiplier} lần tuổi vũ trụ)!',
    t104: 'Thang so sánh logarit (Độ khó theo lũy thừa 10):',
    t105: 'Quy mô số mũ',
    t106: '1. Thử bằng tay: ~10⁰ – 10¹ số',
    t107: 'Vài giây / số',
    t108: '2. Máy thử số nhỏ p ≈ 10⁶:',
    t109: '3. Bitcoin thuật toán thông minh (2¹²⁸ ≈ 10³⁸ bước):',
    t110: '{smartYears} năm ({universeMultiplier} lần tuổi vũ trụ)',
    t111: '4. Toàn bộ không gian khóa Bitcoin (2²⁵⁶ ≈ 1,16 × 10⁷⁷):',
    t112: 'Bất khả thi đối với vũ trụ',
    t113: '💡 Tính xuôi mất 1 giây, tính ngược mất lâu hơn cả tuổi vũ trụ. Đó là lý do khóa công khai được phép công khai.',
    t114: 'Sang phần 3: Tình huống mất khóa ➔',
    t115: ' Tình huống: Mất khóa riêng là mất vĩnh viễn',
    t116: 'Ví của {myName}: 50 xu',
    t117: 'Khóa công khai: 18',
    t118: 'Một cơn gió bất ngờ thổi bay tờ giấy ghi ',
    t119: ' của em xuống cống nước sâu và biến mất hoàn toàn!',
    t120: 'Khóa riêng 12',
    t121: '💸 Thử rút 50 xu ra tiêu',
    t122: '✗ Lỗi: Không thể ký giao dịch vì thiếu khóa riêng!',
    t123: ' Câu hỏi suy ngẫm',
    t124: 'Ai có thể giúp em lấy lại số tiền này nếu em làm mất khóa riêng?',
    t125: '✓ Đúng!',
    t126: ' Chưa chính xác:',
    t127: ' CHÍNH XÁC: Không ai cả — số tiền bị kẹt vĩnh viễn!',
    t128: 'Trong mạng phi tập trung blockchain, không có ngân hàng hay tổng đài để "quên mật khẩu". Quyền sở hữu phụ thuộc 100% vào khóa riêng. Mất khóa riêng đồng nghĩa với mất quyền kiểm soát số tiền vĩnh viễn!',
    t129: ' Số sao đạt được: {so}',
    t130: 'Đang hoàn thành bài học...',
    t131: 'Bảng tra 5^x mod 23 (x = 1..22)',
    t132: 'Bảng tính sẵn kết quả phép tính ',
    t133: ' tương ứng với từng khóa riêng từ 1 đến 22:',
    t134: '🎯 Của {bacAn} (x={x})',
    t135: 'Đóng',
  },
  mayxacminh: {
    t01: 'Máy xác minh chữ ký',
    t02: 'Cách dùng máy',
    t03: 'Cơ chế kiểm tra toán học Schnorr',
    t04: 'Đèn chờ',
    t05: 'Đèn hợp lệ',
    t06: 'Đèn không hợp lệ',
    t07: 'Kéo khóa vào đây',
    t08: 'Khe 1: Khóa công khai',
    t09: '✕ Gỡ',
    t10: 'Gỡ khóa',
    t11: 'Khóa nạp:',
    t12: 'Chưa nạp khóa (kéo từ Danh bạ hoặc Thẻ)',
    t13: 'Chưa nạp khóa (chọn từ Danh bạ hoặc Thẻ)',
    t14: 'Kéo thẻ giao dịch vào đây',
    t15: 'Khe 2: Giao dịch',
    t16: 'Gỡ thẻ',
    t17: 'Giao dịch',
    t18: 'Chưa nạp thẻ giao dịch (kéo thẻ vào đây)',
    t19: 'Chưa nạp thẻ giao dịch',
    t20: 'Đang tính toán kiểm tra chữ ký...',
    t21: 'Sẵn sàng thẩm định chữ ký',
    t22: 'Kiểm tra chữ ký',
    t23: '--- Phiếu kết quả thẩm định ---',
    t24: 'Mã: #{testedKey}',
    t25: 'Chữ ký hợp lệ',
    t26: 'Chữ ký không hợp lệ',
    t27: 'Khóa kiểm tra: ',
    t28: 'Kết luận: ',
    t29: 'Chữ ký này ',
    t30: ' bởi chủ nhân của khóa {testedKey}!',
    t31: 'đúng là được tạo ra',
    t32: ' với khóa {testedKey}!',
    t33: 'không khớp',
  },
  danhba: {
    t01: 'Danh bạ khóa công khai',
    t02: 'Mọi người đều xem và đối chiếu được',
    t03: 'Công khai',
    t07: 'Khóa công khai',
    t08: 'Kéo hoặc chạm để đưa vào Khe Khóa',
  },
  thegiaodich: {
    t04: 'Người gửi',
    t05: '✓ Đang trong máy',
    t06: 'Đưa vào máy',
    t07: 'Nội dung',
    t08: 'Chữ ký số:',
    t09: 'r và s là gì?',
    t10: 'Khóa đính kèm:',
    t11: 'Kéo hoặc chạm để đưa vào Khe Khóa',
    t12: 'Thử khóa này',
    t13: ' Thật',
    t14: ' Giả',
  },
} as const;
